# Service Definitions
services:
  # Nginx: Web Server and Reverse Proxy
  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    environment:
      KEYCLOAK_DOMAIN: ${KEYCLOAK_DOMAIN}  # Domain name for Keycloak
    mem_limit: 50m                         # Maximum memory limit
    mem_reservation: 30m                   # Minimum memory reservation
    container_name: nginx
    volumes:
      - ./nginx-ssl/templates:/etc/nginx/templates  # Nginx configuration templates
      - ./certbot/conf:/etc/letsencrypt             # SSL certificates from Let's Encrypt
      - ./certbot/www:/var/www/certbot              # Webroot for ACME challenges
    ports:
      - 80:80    # HTTP port
      - 443:443  # HTTPS port
    restart: always
    networks:
      - local    # Connects to the local network

  # Certbot: SSL Certificate Management
  certbot:
    image: certbot/certbot:${CERTBOT_VERSION:-latest}
    environment:
      CERTBOT_LETSENCRYPT_EMAIL: ${CERTBOT_LETSENCRYPT_EMAIL}  # Email for Let's Encrypt notifications
      KEYCLOAK_DOMAIN: ${KEYCLOAK_DOMAIN}                      # Domain for the SSL certificate
    mem_limit: 50m       # Maximum memory limit
    mem_reservation: 30m # Minimum memory reservation
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt  # SSL certificates storage
      - ./certbot/www:/var/www/certbot   # Webroot for ACME challenges
    command: certonly --non-interactive --webroot -w /var/www/certbot --email ${CERTBOT_LETSENCRYPT_EMAIL} -d ${KEYCLOAK_DOMAIN} --agree-tos
    depends_on:
      - nginx  # Ensures Nginx is running before Certbot starts

# Network Configuration
networks:
  local:
    ipam:
      config:
        - subnet: ${SUBNET:-172.16.0.0/29}  # Subnet configuration for the local network
